### ISSUE TITLE
Необходим четкий план на MVP

### ISSUE THREAD

**Issue by DmitriyBadeev** [DmitriyBadeev/Sigma.Api#3]
[Здесь](https://github.com/DmitriyBadeev/Sigma.Api/files/7271627/default.docx) кратко описано то, что будет в MVP. Необходимо дополнить экранами мобильного приложения и страницами веб-приложения. Возможно что-то добавить из фич. 

Фигма: https://www.figma.com/file/S88xXZ6LiubNU51c1jlJfR/Sigma?node-id=0%3A1

**Comment by Polly99** [comment]
[investin.docx](https://github.com/DmitriyBadeev/Sigma.Api/files/7285915/investin.docx)
